name: Angular-docker

on:
  push:
    branches:
      - master
      - main
      - next
      - beta
      - "*.x"

env:
  DOCKER_USERNAME: artemsavchuk94
  DOCKER_REPOSITORY_NAME: angular-devops
  
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install -g semantic-release @semantic-release/exec semantic-release-plus @semantic-release-plus/docker
      - run: semantic-release
   
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          
          working-directory: /devops-ui
          command: |
            sudo git pull
            sudo docker-compose pull
            sudo docker-compose up -d --force-recreate

          
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"


              
                 
          
          

         
         
          
          
          
          
